spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/deluxerest
    username: postgres
    password:
    pool:
      enabled: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8082
  error:
    include-stacktrace: never
---
logging:
  level:
    fabianopinto.goproxy.deluxerest: debug
